[colors.primary]
background = "#181926"
foreground = "#cad3f5"

[colors.normal]
black = "#11111b"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#74c7ec"
white = "#cdd6f4"

[colors.bright]
black = "#11111b"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#74c7ec"
white = "#cdd6f4"
